### ISSUE TITLE
Getting this error while installing on pop! os.

### ISSUE THREAD

**Issue by oneironaut2209** [Audio4Linux/Viper4Linux#13]
![image](https://user-images.githubusercontent.com/63645932/125483153-3227689e-7cf6-4b83-bce4-569dda4eca7c.png)

**Comment by fiqrisr** [comment]
same here

**Comment by thequantumcog** [comment]
Cant install on Ubuntu same problem

**Comment by oneironaut2209** [comment]
I actually switched to Arch Linux and now it's working.
