### ISSUE TITLE
Specify the full path

### ISSUE THREAD

**Issue by jeffshee** [Audio4Linux/Viper4Linux#5]
Hi,

Please consider specifying the full path to the binary explicitly, especially when calling the `gst-launch-1.0`, which casing a problem for those who have anaconda in their system. As you can see, when anaconda is installed, their binaries are actually having precedence over the system binaries, resulting in calling the wrong `gst-launch-1.0`.

Thanks.

```
❯ which gst-launch-1.0                                              [14:17:45]
~/anaconda3/bin/gst-launch-1.0
❯ conda deactivate                                                  [14:19:22]

❯ which gst-launch-1.0                                              [14:19:33]
/usr/bin/gst-launch-1.0

❯ echo $PATH                                                        [14:19:47]
/home/jeffshee/anaconda3/condabin:/usr/local/bin:/usr/local/sbin:/usr/share/Modules/bin:/usr/bin:/usr/sbin:/home/jeffshee/bin
```

**Comment by noahbliss** [comment]
@jeffshee I'll leave this open to see if any others have this issue, but I consider respecting the user's path intended functionality.

**Comment by jeffshee** [comment]
What if we just blacklist the binary from anaconda? Since the binary from anaconda doesn't work and giving error.

**Comment by noahbliss** [comment]
One workaround you could do easily is define your PATH variable in the top of the viper script. This should keep the changes local to the viper process environment, but still skip over your anaconda bins.
