### ISSUE TITLE
Does it need gdb as a dependency ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Audio4Linux/Viper4Linux#6]
```
pm@vix ~/.config/viper4linux $ viper start
Killed process. Deleted pidfile.
Unloaded Viper sink.
Spécification de volume invalide
Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
pm@vix ~/.config/viper4linux $ Caught SIGSEGV
exec gdb failed: Aucun fichier ou dossier de ce type
Spinning.  Please run 'gdb gst-launch-1.0 96977' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
^C
pm@vix ~/.config/viper4linux $ sudo eopkg it gdb
Mot de passe : 
Les paquets suivants vont être installés :
gdb  xxhash
Taille totale du/des paquets(s) : 3.21 MB
Il y a des paquets en plus à cause de dépendances. Voulez vous continuer ? (oui/non)oui
Téléchargement 1 / 2
Paquet xxhash trouvé dans le dépôt SolusUnstable
xxhash-0.7.4-5-1-x86_64.eopkg  (28.0 KB)100%    336.88 KB/s [00:00:00] [fini]
Téléchargement 2 / 2
Paquet gdb trouvé dans le dépôt SolusUnstable
gdb-10.1-13-1-x86_64.eopkg     (3.2 MB)100%      1.97 MB/s [00:00:00] [fini]
Installation 1 / 2
xxhash-0.7.4-5-1-x86_64.eopkg [en cache]
Installation de xxhash, version 0.7.4, millésime 5
Extraction des fichiers de xxhash
xxhash installé
Installation 2 / 2
gdb-10.1-13-1-x86_64.eopkg [en cache]
Installation de gdb, version 10.1, millésime 13
Extraction des fichiers de gdb
gdb installé
 [✓] Syncing filesystems                                                success
 [✓] Updating dynamic library cache                                     success
 [✓] Updating manpages database                                         success
pm@vix ~/.config/viper4linux $ viper start
Killed process. Deleted pidfile.
Unloaded Viper sink.
Setting original sink to full volume...
Changing primary sink to Viper...
Moving existing audio streams to Viper...
pm@vix ~/.config/viper4linux $ Caught SIGSEGV
Spinning.  Please run 'gdb gst-launch-1.0 97302' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
```

I’m building Viper on Solus, and while it seems everything went well when following the README.md (Apart from configuring it to the right sink via the configurations files, but i tend to just rely on the GUI instead), I notice that it complain from a missing gdb executable when launching it. Is it only for debugging purposes? (As it isn’t stated in the Debian/Arch dependencies).

**Comment by timschneeb** [comment]
GDB is not required. Actually, the whole Viper plugin crashes here.
In your case, it would be useful because you can use gdb to debug the crash that happened here.
It is very likely that is crash is caused by corrupt audio.conf file, you can try to replace that file (~/.config/viper4linux/audio.conf) with the [default version](https://github.com/Audio4Linux/Viper4Linux/blob/master/viper4linux/audio.conf) stored in this repo.

If that doesn't solve the crash, I can give you instructions on how to debug this with gdb, if you happen to need them.

**Comment by PoorPocketsMcNewHold** [comment]
I’ve resolved it. I’ve had made two mistakes :

*   The first being two missing dependencies : `gstreamer-1.0-plugins-bad-devel` & `pulseaudio-devel`. Gstreamer-bad was listed on the GUI page and the GUI make file also requested libpulse.
*   The second mistake, was a line I’ve omitted from Step 4, where a different specific directory was specified for Solus.

Thanks for the quick answer, once again.
