### ISSUE TITLE
Automated the Installation Process

### ISSUE THREAD

**Issue by SamarthH** [Audio4Linux/Viper4Linux#9]
@noahbliss I have created a script for pacstall (https://github.com/Henryws/pacstall) which is a new project for making something like the AUR for Ubuntu. Hopefully, this would help

**Comment by noahbliss** [comment]
Awesome! Would you mind submitting a draft for the readme update? Would love to let our users know about their expanded options!

**Comment by SamarthH** [comment]
I have submitted a pull request for the same. Thanks

**Comment by noahbliss** [comment]
Approved as https://github.com/Audio4Linux/Viper4Linux/pull/10 thanks for the help!
